### ISSUE TITLE
Review access layers for first release

### ISSUE THREAD

**Issue by burkmarr** [BiologicalRecordsCentre/DECIDE-app#9]
@mjopocock @TMondain @AugustT 

Iain copied Thomas' access data to the SAN so I've spent the day tweaking the app to use this and deploying it to staging. 

**https://decide.staging.ceh.ac.uk/** (remember you need to be on VPN to reach the staging cluster)

Can the three of you take a look at this before I include it in the production release? Some points to consider:

- There are now a lot of access layers (6), each of which requires a round trip to the server to extract and download to the app.
- I've only put three of them on by default to speed things up a bit.
- It feels to me a bit like we are overfacing people with these for the intial release - they certainly take up a lot of space on the options sidebar. Should be consider reducing for the first release?
- The stuff from the London area is very dense and consequently slow to process. Also much of it doesn't seem to add any value to the basemap - simply following footpaths in urban areas, so this needs reviewing.

Can you let me know what you think and whether this should go forward into the first production release as is or tweaked?

**Comment by mjopocock** [comment]
Hi @burkmarr,
Lots to think about here! I think that it is pretty much okay for the first release. Getting feedback from people is probably more important than perfecting it now!
My opinion for quick things now:
- load only greenspace by default. Definately turn access points off.
- greenspace is red - which overlays the yellow-red DECIDE layer. Possibly change it to grey?
- footpaths could be mid grey rather than black to reduce their dominance. (The London switch is sensible.)
- CROW open access land only seems to work in some places. Like the greenspace layer, the colour confuses the red DECIDE scores underneath. (Although it can be turned off easily).
- Add "(limited availability)" for the layers that aren't comprehensive for now?
- NT land seems a bit variable - it only picks up their countryside, not their properties.
Hope that helps for now.

**Comment by burkmarr** [comment]
@mjopocock - can you point to me to areas where the data appears incomplete for 1) CROW and 2) NT and any other layers where you've noticed it? (I need to check that it's not a problem with the scripts serving the data.)

@TMondain - does Michael's comment about NT data chime with what you know about the data provenance?

**Comment by TMondain** [comment]
@burkmarr https://uk-nationaltrust.opendata.arcgis.com/ This is where the data were downloaded from but it doesn't say anything about not including their properties. It is mapped at quite a coarse scale though (1:50000) but that wouldn't really explain it. I'll have a dig to see if I can find properties.

**Comment by burkmarr** [comment]
Okay - don't spend much time on it Thomas - it's not a show stopper, certainly not for this initial release. In terms of access for biological recording, the properties aren't as important as the estates.

**Comment by mjopocock** [comment]
Ah, I think the properties (e.g. Basildon Park near Streatley, West Berks) have 'limited access', so maybe it should be "open access National Trust land"?

**Comment by mjopocock** [comment]
However checking further, the two sites very near Streatley/Goring aren't showing. It's not vital for this release - but it is strange.
